/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace MusicStore {
  export type AlbumStruct = {
    index: PromiseOrValue<BigNumberish>;
    uid: PromiseOrValue<string>;
    title: PromiseOrValue<string>;
    price: PromiseOrValue<BigNumberish>;
    quantity: PromiseOrValue<BigNumberish>;
  };

  export type AlbumStructOutput = [
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber
  ] & {
    index: BigNumber;
    uid: string;
    title: string;
    price: BigNumber;
    quantity: BigNumber;
  };
}

export interface MusicStoreInterface extends utils.Interface {
  functions: {
    "addAlbum(string,string,uint256,uint256)": FunctionFragment;
    "albums(uint256)": FunctionFragment;
    "allAlbums()": FunctionFragment;
    "buy(uint256)": FunctionFragment;
    "currentIndex()": FunctionFragment;
    "currentOrderId()": FunctionFragment;
    "delivered(uint256)": FunctionFragment;
    "orders(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addAlbum"
      | "albums"
      | "allAlbums"
      | "buy"
      | "currentIndex"
      | "currentOrderId"
      | "delivered"
      | "orders"
      | "owner"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addAlbum",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "albums",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "allAlbums", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "currentIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentOrderId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "delivered",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addAlbum", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "albums", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allAlbums", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentOrderId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "delivered", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;

  events: {
    "AlbumBought(string,string,address,uint256)": EventFragment;
    "OrderDelivered(string,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AlbumBought"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OrderDelivered"): EventFragment;
}

export interface AlbumBoughtEventObject {
  uid: string;
  rawUid: string;
  customer: string;
  timestamp: BigNumber;
}
export type AlbumBoughtEvent = TypedEvent<
  [string, string, string, BigNumber],
  AlbumBoughtEventObject
>;

export type AlbumBoughtEventFilter = TypedEventFilter<AlbumBoughtEvent>;

export interface OrderDeliveredEventObject {
  albumUid: string;
  customer: string;
}
export type OrderDeliveredEvent = TypedEvent<
  [string, string],
  OrderDeliveredEventObject
>;

export type OrderDeliveredEventFilter = TypedEventFilter<OrderDeliveredEvent>;

export interface MusicStore extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MusicStoreInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addAlbum(
      uid: PromiseOrValue<string>,
      title: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    albums(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, BigNumber] & {
        index: BigNumber;
        uid: string;
        title: string;
        price: BigNumber;
        quantity: BigNumber;
      }
    >;

    allAlbums(
      overrides?: CallOverrides
    ): Promise<[MusicStore.AlbumStructOutput[]]>;

    buy(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    currentIndex(overrides?: CallOverrides): Promise<[BigNumber]>;

    currentOrderId(overrides?: CallOverrides): Promise<[BigNumber]>;

    delivered(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    orders(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, number] & {
        orderId: BigNumber;
        albumUid: string;
        customer: string;
        orderAt: BigNumber;
        status: number;
      }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;
  };

  addAlbum(
    uid: PromiseOrValue<string>,
    title: PromiseOrValue<string>,
    price: PromiseOrValue<BigNumberish>,
    quantity: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  albums(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, BigNumber, BigNumber] & {
      index: BigNumber;
      uid: string;
      title: string;
      price: BigNumber;
      quantity: BigNumber;
    }
  >;

  allAlbums(overrides?: CallOverrides): Promise<MusicStore.AlbumStructOutput[]>;

  buy(
    _index: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  currentIndex(overrides?: CallOverrides): Promise<BigNumber>;

  currentOrderId(overrides?: CallOverrides): Promise<BigNumber>;

  delivered(
    _index: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  orders(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, BigNumber, number] & {
      orderId: BigNumber;
      albumUid: string;
      customer: string;
      orderAt: BigNumber;
      status: number;
    }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addAlbum(
      uid: PromiseOrValue<string>,
      title: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    albums(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, BigNumber] & {
        index: BigNumber;
        uid: string;
        title: string;
        price: BigNumber;
        quantity: BigNumber;
      }
    >;

    allAlbums(
      overrides?: CallOverrides
    ): Promise<MusicStore.AlbumStructOutput[]>;

    buy(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    currentIndex(overrides?: CallOverrides): Promise<BigNumber>;

    currentOrderId(overrides?: CallOverrides): Promise<BigNumber>;

    delivered(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    orders(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, number] & {
        orderId: BigNumber;
        albumUid: string;
        customer: string;
        orderAt: BigNumber;
        status: number;
      }
    >;

    owner(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AlbumBought(string,string,address,uint256)"(
      uid?: PromiseOrValue<string> | null,
      rawUid?: null,
      customer?: PromiseOrValue<string> | null,
      timestamp?: PromiseOrValue<BigNumberish> | null
    ): AlbumBoughtEventFilter;
    AlbumBought(
      uid?: PromiseOrValue<string> | null,
      rawUid?: null,
      customer?: PromiseOrValue<string> | null,
      timestamp?: PromiseOrValue<BigNumberish> | null
    ): AlbumBoughtEventFilter;

    "OrderDelivered(string,address)"(
      albumUid?: PromiseOrValue<string> | null,
      customer?: PromiseOrValue<string> | null
    ): OrderDeliveredEventFilter;
    OrderDelivered(
      albumUid?: PromiseOrValue<string> | null,
      customer?: PromiseOrValue<string> | null
    ): OrderDeliveredEventFilter;
  };

  estimateGas: {
    addAlbum(
      uid: PromiseOrValue<string>,
      title: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    albums(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allAlbums(overrides?: CallOverrides): Promise<BigNumber>;

    buy(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    currentIndex(overrides?: CallOverrides): Promise<BigNumber>;

    currentOrderId(overrides?: CallOverrides): Promise<BigNumber>;

    delivered(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    orders(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addAlbum(
      uid: PromiseOrValue<string>,
      title: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    albums(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allAlbums(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    buy(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    currentIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currentOrderId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    delivered(
      _index: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    orders(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
